from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path


class IntegrityError(RuntimeError):
    pass


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build_manifest_for_executable(executable: Path) -> dict:
    return {
        "version": 2,
        "executable": executable.name,
        "sha256": _sha256(executable),
    }


def write_manifest(executable: Path | None = None) -> Path:
    exe = executable or Path(sys.executable)
    target = exe.resolve().parent / "security_manifest.json"
    target.write_text(json.dumps(build_manifest_for_executable(exe.resolve()), indent=2), encoding="utf-8")
    return target


def verify_manifest() -> None:
    """Best-effort anti-tamper check for a packaged build.

    Source/IDE runs are intentionally not blocked. A packaged executable must have a
    sidecar security_manifest.json generated by build_exe.bat. This detects accidental
    or casual modification of the shipped EXE; it is not unbreakable DRM.
    """
    if not getattr(sys, "frozen", False):
        return
    if os.getenv("MIZU_SKIP_INTEGRITY", "") == "1":
        return
    exe = Path(sys.executable).resolve()
    manifest = exe.parent / "security_manifest.json"
    if not manifest.exists():
        raise IntegrityError("Brak manifestu integralności obok MizuLauncher.exe.")
    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
        expected = data.get("sha256")
    except Exception as exc:
        raise IntegrityError("Manifest integralności jest uszkodzony.") from exc
    if not expected or _sha256(exe) != expected:
        raise IntegrityError("Plik MizuLauncher.exe został zmodyfikowany.")
